package com.opponify.service

import com.fasterxml.jackson.databind.ObjectMapper
import com.opponify.api.ApiException
import com.opponify.opportunity.domain.OpportunityStatus
import com.opponify.persistence.OpportunityRepository
import org.springframework.beans.factory.annotation.Value
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.time.Duration
import java.time.Instant
import java.util.UUID

@Service
class OpportunityLifecycleService(private val jdbc:JdbcTemplate,private val opportunities:OpportunityRepository,private val mapper:ObjectMapper,@Value("\${opponify.scheduling.material-change-expiry}") private val expiry:Duration){
    @Transactional fun close(actor:UUID,id:UUID){val o=opportunities.find(id)?:throw ApiException(404,"OPPORTUNITY_NOT_FOUND","Opportunity not found.");authorizeCreator(actor,o.creatorUserId,o.creatorTeamId);jdbc.update("UPDATE opportunities SET status='CLOSED',updated_at=NOW() WHERE id=? AND status='OPEN'",id)}
    @Transactional fun cancel(actor:UUID,id:UUID){val o=opportunities.find(id)?:throw ApiException(404,"OPPORTUNITY_NOT_FOUND","Opportunity not found.");authorizeCreator(actor,o.creatorUserId,o.creatorTeamId);jdbc.update("UPDATE opportunities SET status='CANCELLED',updated_at=NOW() WHERE id=? AND status IN ('DRAFT','OPEN','CLOSED')",id)}
    @Transactional fun reopen(actor:UUID,id:UUID){val o=opportunities.find(id)?:throw ApiException(404,"OPPORTUNITY_NOT_FOUND","Opportunity not found.");authorizeCreator(actor,o.creatorUserId,o.creatorTeamId);if(o.status!=OpportunityStatus.CLOSED)throw ApiException(409,"OPPORTUNITY_NOT_CLOSED","Only closed opportunities can be reopened.");val accepted=jdbc.queryForObject("SELECT COUNT(*) FROM participation_requests WHERE opportunity_id=? AND status='ACCEPTED'",Int::class.java,id)?:0;if(accepted>=o.targetCapacity)throw ApiException(409,"NO_VACANCY","Reopening cannot exceed current target capacity.");jdbc.update("UPDATE opportunities SET status='OPEN',updated_at=NOW() WHERE id=?",id)}
    @Transactional fun proposeChange(actor:UUID,id:UUID,type:String,previous:Any,proposed:Any):UUID{val o=opportunities.find(id)?:throw ApiException(404,"OPPORTUNITY_NOT_FOUND","Opportunity not found.");authorizeCreator(actor,o.creatorUserId,o.creatorTeamId);if(o.status !in setOf(OpportunityStatus.OPEN,OpportunityStatus.CLOSED))throw ApiException(409,"OPPORTUNITY_NOT_EDITABLE","Opportunity is not editable.");val change=UUID.randomUUID();jdbc.update("UPDATE opportunity_changes SET status='SUPERSEDED' WHERE opportunity_id=? AND status='PROPOSED'",id);jdbc.update("INSERT INTO opportunity_changes(id,opportunity_id,change_type,previous_value,proposed_value,proposer_user_id,expires_at) VALUES(?,?,?,?::jsonb,?::jsonb,?,?)",change,id,type,mapper.writeValueAsString(previous),mapper.writeValueAsString(proposed),actor,Instant.now().plus(expiry));return change}
    @Transactional fun confirmChange(actor:UUID,changeId:UUID){val row=jdbc.queryForList("SELECT * FROM opportunity_changes WHERE id=? AND status='PROPOSED'",changeId).firstOrNull()?:throw ApiException(404,"CHANGE_NOT_FOUND","Change not found.");val o=opportunities.find(row["opportunity_id"] as UUID)?:throw ApiException(404,"OPPORTUNITY_NOT_FOUND","Opportunity not found.");if((row["expires_at"] as java.sql.Timestamp).toInstant()<=Instant.now()){jdbc.update("UPDATE opportunity_changes SET status='EXPIRED' WHERE id=?",changeId);throw ApiException(409,"CHANGE_EXPIRED","Change expired.")};val actorAllowed=actor==o.creatorUserId || (o.creatorTeamId!=null && canManageTeam(actor,o.creatorTeamId));if(!actorAllowed)throw ApiException(403,"CREATOR_AUTHORITY_REQUIRED","Creator authority required.");jdbc.update("INSERT INTO opportunity_change_confirmations(change_id,user_id) VALUES(?,?) ON CONFLICT DO NOTHING",changeId,actor);val affectedUsers=jdbc.queryForList("SELECT DISTINCT requester_user_id FROM participation_requests WHERE opportunity_id=? AND status='ACCEPTED' AND requester_user_id IS NOT NULL",o.id).map{it["requester_user_id"] as UUID}
        val affectedTeamReps=jdbc.queryForList("SELECT DISTINCT ON (r.requester_team_id) m.user_id FROM participation_requests r JOIN team_memberships m ON m.team_id=r.requester_team_id WHERE r.opportunity_id=? AND r.status='ACCEPTED' AND r.requester_team_id IS NOT NULL AND m.status='ACTIVE' AND m.role IN ('CAPTAIN','MANAGER') ORDER BY r.requester_team_id,CASE m.role WHEN 'CAPTAIN' THEN 0 ELSE 1 END,m.user_id",o.id).map{it["user_id"] as UUID}
        val affected=(affectedUsers+affectedTeamReps).distinct();val confirmed=jdbc.queryForList("SELECT user_id FROM opportunity_change_confirmations WHERE change_id=?",changeId).map{it["user_id"] as UUID};if(affected.any{it !in confirmed})return;apply(o.id,row["change_type"] as String,mapper.readTree(row["proposed_value"].toString()));jdbc.update("UPDATE opportunity_changes SET status='CONFIRMED' WHERE id=?",changeId)}
    private fun apply(id:UUID,type:String,v:com.fasterxml.jackson.databind.JsonNode){when(type){"TIME"->{jdbc.update("UPDATE opportunities SET start_at=?,end_at=?,time_type=?,updated_at=NOW() WHERE id=?",v.get("startAt")?.asText()?.let(Instant::parse),v.get("endAt")?.asText()?.let(Instant::parse),v.get("timeType")?.asText(),id)};"FACILITY"->jdbc.update("UPDATE opportunities SET facility_id=?,updated_at=NOW() WHERE id=?",v.get("facilityId")?.asText()?.let(UUID::fromString),id);"MINIMUM"->{val min=v.get("minimumParticipation").asInt();val target=jdbc.queryForObject("SELECT target_capacity FROM opportunities WHERE id=?",Int::class.java,id)!!;if(min<=0||min>target)throw ApiException(422,"INVALID_MINIMUM","Invalid minimum participation.");jdbc.update("UPDATE opportunities SET minimum_participation=?,updated_at=NOW() WHERE id=?",min,id)};"LOCATION"->jdbc.update("UPDATE opportunities SET town=?,location_type=?,free_form_location=?,latitude=?,longitude=?,updated_at=NOW() WHERE id=?",v.get("town")?.asText(),v.get("locationType")?.asText(),v.get("freeFormLocation")?.asText(),v.get("latitude")?.asDouble(),v.get("longitude")?.asDouble(),id);else->throw ApiException(422,"UNSUPPORTED_CHANGE","Unsupported opportunity change type.")}}
    private fun authorizeCreator(actor:UUID,user:UUID?,team:UUID?){if(actor!=user && (team==null||!canManageTeam(actor,team)))throw ApiException(403,"CREATOR_AUTHORITY_REQUIRED","Creator authority required.")}
    private fun canManageTeam(actor:UUID,team:UUID)=jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM team_memberships WHERE team_id=? AND user_id=? AND status='ACTIVE' AND role IN ('CAPTAIN','MANAGER'))",Boolean::class.java,team,actor)?:false
}
